language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: VoApRbHF2QVSWgc7H/5n7c9cTqysqgU6oW4JGuoZOCLP0fh4lsxf0hYOqAXQMAtnrFHg9r6WHjU6A2eL1ncwPcPN4hhBlwvj6xdL5RwnkiE7FyJoq6f4pUtd0Bp/4sgz3aI+DuDFdozLJGwoPAM5o3nelJsHitYGFV+WkShL0x0=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: LwOrT09zwQCp4eDZMPv7M/ymQBghr/ASKo1pOMD0osVHrQAnrgZH14pOXcOUEkzJDrbmhUeZZ/tt3a/oBomfkPqHQh/fSAPQWUFbUsWm6gk4Lzf/NJj1+YHJRHTW5iFWMZVOuTESFt7hrTaRFxtLhVvaURpVvsfGWxiTQ9+kQWU=
sudo: false
