language: node_js
node_js:
- '0.11'
sudo: false
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: jubLUJTZncFnbZaGUuytJSpyeFy+YiOHUYbNKZzE2Qt1Is3xYl+DZGkPpLEivOYVIG+BAaVw7ed4mkd7KeGx65vXCoRL6y71rElA8Y8l19ev41Dk8CV9DWJ679k7K5OU6mqaSGuRkt1UsGKaoz7EStH6RDhzFBpmcDYV7L7PXVI=
notifications:
  email: false
  slack:
    secure: f6YudPqske+Dp9z6oXEa/GlbtzQNGTte8kSmNgI0CLr6rAqtcyKBWth2tQTxrwdFUoZHwrADQtZVWHOpGqhgfoQ2jvXoO7WCnAPcaKa5o6bdsARaJcNyj7iK3rEcVms9r5pxxxqkArIm9v7syi1IoPTdGnxBUEL41tIPsgQjRZg=
